### ISSUE TITLE
Let gateway and API use different hosts from each other

### ISSUE THREAD

**Issue by sonatagreen** [ipfs/ipfs-firefox-addon#249]
Currently, the addon expects that the gateway and API must use the same host (default localhost). While IPFS's default behavior is indeed to bind both gateway and API to 127.0.0.1, the config supports binding each of them to a different address. The addon should ideally be correspondingly flexible, to accommodate such configurations.

**Comment by lidel** [comment]
Good idea!
I already re-implemented this and versions 2.x.x have separate URLs for both:

> ![2017-05-17 08_24_12-add-ons manager](https://cloud.githubusercontent.com/assets/157609/26141057/3c64fe26-3ada-11e7-90c7-c4cf067a8f89.png)

It will take some time before we release 2.x.x as a stable version, but if you like to test experimental things  you can install it from Development Channel:

- https://addons.mozilla.org/en-US/firefox/addon/ipfs-gateway-redirect/versions/beta
