### ISSUE TITLE
Browser extension doesn't appear at the top right anymore

### ISSUE THREAD

**Issue by diasdavid** [ipfs/ipfs-firefox-addon#251]
After installing the extension again, I no longer see it at top right. I see there was a recent release on May 21, did something change? 

![image](https://cloud.githubusercontent.com/assets/1211152/26289077/6a4715b6-3e6a-11e7-8791-a552503505b7.png)

**Comment by lidel** [comment]
WebExtension is released in [Development Channel](https://addons.mozilla.org/en-US/firefox/addon/ipfs-gateway-redirect/versions/beta) as `2.x`. 

`1.x` is a stable, legacy version from January. It SHOULD work until Firefox 57.  

What FF version are you using?  
Can you open Browser Console (<kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>j</kbd>) and see if there are any errors specific to the add-on?
If not, maybe.. it just got moved to hamburger menu?

**Comment by diasdavid** [comment]
This is what I have: 

![image](https://cloud.githubusercontent.com/assets/1211152/26309582/8b140964-3ecb-11e7-9711-54d7dacf92c6.png)

**Comment by VictorBjelkholm** [comment]
Press on "Customize" and you should be able to see all the additional
toolbar-buttons you can add

**Comment by diasdavid** [comment]
doh! :D thanks @VictorBjelkholm
